repos:
- repo: local
  hooks:
  - id: format
    name: ruff format
    language: system
    files: \.py$
    entry: ruff format
  - id: ruff
    name: ruff
    language: system
    files: \.py$
    entry: ruff check --fix
